// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swufszgxoignnhxhzjzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dWZzemd4b2lnbm5oeGh6anppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NjgwNjcsImV4cCI6MjA1NDA0NDA2N30.KXyG35oEsNKr8-yAoUYrvAPuf7ndeGmL3pc658ha3gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);